export const icons = {
    DARK_MODE: 'nights_stay',
    LIGHT_MODE: 'light_mode',
    LANGUAGE: 'translate',
    HOME: 'home',
    ACCOUNT: 'person',
    MENU: 'menu',
    CLOSE: 'close',
    LOGIN: 'login',
    CHECK: 'check',
    SEARCH: 'search',
    BACK: 'chevron_left',
    NEXT: 'navigate_next',
    LINE: 'horizontal_rule',
    CONFERENCE: 'videocam',
    EYE: 'visibility',
    EYE_OFF: 'visibility_off',
    FILE: 'attach_file',
    MORE: 'more_vert',
    REPORT: 'outlined_flag',
    LOGOUT: 'logout',
    SHARE: 'share',
    FAVORITE_BORDER: 'star_outline',
    FAVORITE: 'favorite',
    DELETE: 'delete_outline',
    CHANGE: 'published_with_changes',
}