export const icons = {
    DARK_MODE: 'nights_stay',
    LIGHT_MODE: 'light_mode',
    LANGUAGE: 'translate',
    HOME: 'home',
    ACCOUNT: 'person',
    MENU: 'menu',
    CLOSE: 'close',
    LOGIN: 'login',
    CHECK: 'check',
    SEARCH: 'search',
    BACK: 'chevron_left',
    NEXT: 'navigate_next',
    LINE: 'horizontal_rule',
}